version: '3.8'

services:
  postgres-db:
      image: postgres
      container_name: postgres-container
      environment:
        POSTGRES_PASSWORD: admin123
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
