"""create_ads_model

Revision ID: 55763d770475
Revises: c79b0938ea4b
Create Date: 2024-03-31 21:42:58.626643

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "55763d770475"
down_revision = "c79b0938ea4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ads",
        sa.Column("ad_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.user_id"],
        ),
        sa.PrimaryKeyConstraint("ad_id"),
    )
    op.add_column(
        "user_account", sa.Column("full_name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "user_account", sa.Column("is_customer", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "is_customer")
    op.drop_column("user_account", "full_name")
    op.drop_table("ads")
    # ### end Alembic commands ###
