"""modify_ad__model

Revision ID: ddf7c778e3a8
Revises: fa74b460818d
Create Date: 2024-04-10 19:26:18.789263

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ddf7c778e3a8"
down_revision = "fa74b460818d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("ad_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ads.ad_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("ads", "images")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ads", sa.Column("images", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_table("images")
    # ### end Alembic commands ###
