"""change_ad_model

Revision ID: fa74b460818d
Revises: 46ce21a0cccf
Create Date: 2024-04-07 22:06:17.196481

"""

# revision identifiers, used by Alembic.
revision = "fa74b460818d"
down_revision = "46ce21a0cccf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
